steps:
  - label: Build and Push App Container
    command: ./scripts/build_container
    plugins:
      - docker-login#v2.1.0:
          username: rohitjm
          password-env: MY_DOCKER_LOGIN_PASSWORD
